### PR TITLE
[CSV-306] followup to fix deprecated method in user guide

### PR DESCRIPTION
**Pull request by samabcde**
Follow up from comment https://github.com/apache/commons-csv/pull/324#pullrequestreview-1407063521

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Thank you!!!

**Comment by kinow** [comment]
Merged, thanks!

**Comment by garydgregory** [comment]
@kinow 
Should this be mentioned in changes.xml?

**Comment by kinow** [comment]
> @kinow Should this be mentioned in changes.xml?

Already done so. I re-used the entry for the issue CSV-306 you merged, adding this PR as it complements that other one.

**Pull request merged**
