### PR TITLE
export page data from db

### PR DESCRIPTION
**Pull request by shootercheng**

### CODE REVIEW

**Comment by shootercheng** [comment]
Failed to execute goal org.apache.rat:apache-rat-plugin:0.13:check (rat-check) on project commons-csv: Execution rat-check of goal org.apache.rat:apache-rat-plugin:0.13:check failed: Plugin org.apache.rat:apache-rat-plugin:0.13 or one of its dependencies could not be resolved: Could not transfer artifact commons-collections:commons-collections:jar:3.2.2 from/to google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/): GET request of: commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar from google-maven-central failed: Connection reset

**Comment by shootercheng** [comment]
> [Coverage Status](https://coveralls.io/builds/28894087)
> 
> Coverage decreased (-1.3%) to 91.879% when pulling **[f98dfe2](https://github.com/apache/commons-csv/commit/f98dfe2e8b8169c42e7aaa2692389dcc132f1bd9) on shootercheng:master** into **[e503c56](https://github.com/apache/commons-csv/commit/e503c568a10ae42364a94695b8505bcb4db28969) on apache:master**.

所有的方法都测试了，这个覆盖率检测有bug

**Comment by garydgregory** [comment]
This ticket has no description so I have no idea what the intent is here. The lack of Javadoc does not help either.

**Comment by shootercheng** [comment]
今天添加JavaDoc ，实现分页查询导出数据库的数据到 CSV


 
---Original---

**Comment by shootercheng** [comment]
> intent



> This ticket has no description so I have no idea what the intent is here. The lack of Javadoc does not help either.

you can see the method DbQueryExportTest.testExport(),  this test method will export querying page data from db

**Comment by garydgregory** [comment]
> > intent
> 
> > This ticket has no description so I have no idea what the intent is here. The lack of Javadoc does not help either.
> 
> you can see the method DbQueryExportTest.testExport(), this test method will export querying page data from db

@shootercheng 
I'm sorry so say that you're not helping your PR here :-( You should provide some kind of description for this PR so that people can learn what problem this PR attempts to solve and how. This would then allow reviewers to try to understand if this code belongs here and how it can fit in. I suppose you could fill in the Javadoc at a later phase of your development (but before any merge into Commons CSV.)

If you want to export database rows, you can use `org.apache.commons.csv.CSVPrinter.printRecords(ResultSet)` which works with Java's own JDBC framework. The printer class also provides other types of services to create CSV files.

More importantly, I see zero reuse of Commons CSV's code for which this PR seems to duplicate features like using your `ExportParam` instead of CVS's `CSVFormat`. It seems this PR is complete;y standalone code from Commons CSV since it does not reuse any of Commons CSV's code. Why would it belong within Commons CSV?

**Comment by shootercheng** [comment]
> > > intent
> > 
> > 
> > > This ticket has no description so I have no idea what the intent is here. The lack of Javadoc does not help either.
> > 
> > 
> > you can see the method DbQueryExportTest.testExport(), this test method will export querying page data from db
> 
> @shootercheng
> I'm sorry so say that you're not helping your PR here :-( You should provide some kind of description for this PR so that people can learn what problem this PR attempts to solve and how. This would then allow reviewers to try to understand if this code belongs here and how it can fit in. I suppose you could fill in the Javadoc at a later phase of your development (but before any merge into Commons CSV.)
> 
> If you want to export database rows, you can use `org.apache.commons.csv.CSVPrinter.printRecords(ResultSet)` which works with Java's own JDBC framework. The printer class also provides other types of services to create CSV files.
> 
> More importantly, I see zero reuse of Commons CSV's code for which this PR seems to duplicate features like using your `ExportParam` instead of CVS's `CSVFormat`. It seems this PR is complete;y standalone code from Commons CSV since it does not reuse any of Commons CSV's code. Why would it belong within Commons CSV?

之前使用过 printRecords(ResultSet) 去导出 csv 数据，但是数据量比较大的时候，导出有问题，所以我就加了这个导出方法，确实好像可以单独出来建一个工程了，不过放在这里也没啥问题呀，增强了原来的导出功能呀

**Comment by shootercheng** [comment]
I am so sorry , I have closed it.


 
---Original---

**Comment by garydgregory** [comment]
Google translate says:

> I have used printRecords (ResultSet) to export csv data before, but when the amount of data is relatively large, there is a problem with the export, so I added this export method, and it seems that it can be built separately, but there is nothing here Problem, enhanced the original export function


I do not see enhancements in this PR that has anything to do with JDBC. What am I missing?

**Comment by ajamesa** [comment]
> Google translate says:
> 
> > I have used printRecords (ResultSet) to export csv data before, but when the amount of data is relatively large, there is a problem with the export, so I added this export method, and it seems that it can be built separately, but there is nothing here Problem, enhanced the original export function
> 
> I do not see enhancements in this PR that has anything to do with JDBC. What am I missing?

ResultSet is very primitive, we do not use JDBC in web projects

**Comment by garydgregory** [comment]
> > Google translate says:
> > > I have used printRecords (ResultSet) to export csv data before, but when the amount of data is relatively large, there is a problem with the export, so I added this export method, and it seems that it can be built separately, but there is nothing here Problem, enhanced the original export function
> > 
> > 
> > I do not see enhancements in this PR that has anything to do with JDBC. What am I missing?
> 
> ResultSet is very primitive, we do not use JDBC in web projects

How do you extract data from your database? Hibernate?

**Comment by shootercheng** [comment]
> Google translate says:
> 
> > I have used printRecords (ResultSet) to export csv data before, but when the amount of data is relatively large, there is a problem with the export, so I added this export method, and it seems that it can be built separately, but there is nothing here Problem, enhanced the original export function
> 
> I do not see enhancements in this PR that has anything to do with JDBC. What am I missing?
Please see my demo project for export page data from db, it takes less time
https://github.com/shootercheng/batch/tree/export
`
21:19:59.967 [main] DEBUG com.single.batch.mapper.BatchLabelMapper.selectPage - ==>  Preparing: select concat_ws(',', id, ifnull(parent,''), ifnull(code,''), ifnull(status,''), ifnull(type,''), ifnull(customer_id,''), ifnull(operator_id,''), ifnull(reseller_id,''), ifnull(user_id,''), ifnull(product_id,''), ifnull(batch,''), ifnull(query_times,''), ifnull(first_time,''), ifnull(create_time,''), ifnull(update_time,'') ) from label_1 limit ?,? 
21:19:59.968 [main] DEBUG com.single.batch.mapper.BatchLabelMapper.selectPage - ==> Parameters: 990000(Integer), 10000(Integer)
21:20:01.126 [main] DEBUG com.single.batch.mapper.BatchLabelMapper.selectPage - <==      Total: 10000
21:20:01.131 [main] DEBUG org.apache.ibatis.transaction.jdbc.JdbcTransaction - Resetting autocommit to true on JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@59309333]
21:20:01.131 [main] DEBUG org.apache.ibatis.transaction.jdbc.JdbcTransaction - Closing JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@59309333]
time 64218 ms
`

**Comment by shootercheng** [comment]
time 64218 ms 

https://github.com/shootercheng/batch/tree/export

How to use JDBC  in this demo web project? You should add more base code.Show me wasting less time for using commons-csv !

**Comment by shootercheng** [comment]
> Google translate says:
> 
> > I have used printRecords (ResultSet) to export csv data before, but when the amount of data is relatively large, there is a problem with the export, so I added this export method, and it seems that it can be built separately, but there is nothing here Problem, enhanced the original export function
> 
> I do not see enhancements in this PR that has anything to do with JDBC. What am I missing?

time 64218 ms

https://github.com/shootercheng/batch/tree/export

How to use JDBC in this demo web project? You should add more base code.Show me wasting less time for using commons-csv !

**Comment by garydgregory** [comment]
If you are looking for help on how to use JDBC, then start here: https://docs.oracle.com/javase/tutorial/jdbc/basics/index.html

Once you know how to use JDBC to procure a JDBC `ResultSet`, then using Commons CSV is as simple as calling `CSVPrinter.printRecords(ResultSet)`

**Pull request closed without merging**
