### PR TITLE
refactor: made some minor refactorings.

### PR DESCRIPTION
**Pull request by RHSaliya**
I'm learning how to contribute to open-source projects. This is my first pull request. So, I have not made major changes.

### CODE REVIEW

**Comment by garydgregory** [comment]
This looks like a change for change's sake, without explanation,  so -1 from me.

**Comment by RHSaliya** [comment]
Sorry, I will make more changes and make a pull request.

**Review by gallegosdamian505 — APPROVED** [review]

**Comment by garydgregory** [comment]
Hi @RHSaliya 
-1: sorry but this looks like changes for changes sake.
You can look at Jira for bug reports and feature requests.

**Comment by garydgregory** [comment]
Closing: no reply.

**Pull request closed without merging**
