### PR TITLE
Fix for incorrect handling of embedded quotes when printing from Read…

### PR DESCRIPTION
**Pull request by arcticgeek**
Fix for incorrect handling of embedded quotes when printing from Reader and to related test; added new test class to further exercise CSVFormat.printWithQuotes(Reader,Appendable) for expected behavior. CSV-263

### CODE REVIEW

**Comment by garydgregory** [comment]
May you please rebase on master?

**Comment by arcticgeek** [comment]
Hi Gary, I tried this morning to do what you have reasonably asked of me. While trying "rebase my patch" on master, I think what I've done now is merged all of the changes which have occurred in master since my fork into my fork instead of committing *just* my changes updated relative to what is *now* on master. And I don't know how to fix it so that my patch is nice and clean like I took the time to do originally a year ago.

My patch in this pull request is an important fix that I would like to see merged. I understand abstractly what you want me to do, and making the code changes was easy enough, but I just don't understand git well enough to satisfy your ask. I'm willing to try to fix this with your guidance but otherwise I don't know how to proceed and I'm sorry about that.

**Comment by garydgregory** [comment]
@arcticgeek 
Just look at the Files tab in GitHub and check that the changes are what you want.

**Review by arcticgeek — COMMENTED** [review]
This simple refactoring of CSVFormat.printWithQuotes(Reader, Appendable) addresses the embedding issue and the included test case is valid for exercising this method to ensure correct behavior in the future.

**Comment by garydgregory** [comment]
@arcticgeek 
The build fails. Please see the GitHub logs.

**Review by arcticgeek — COMMENTED** [review]
The original test case CSVFormatTest.testPrintWithQuotes() was confirming the incorrect behavior and somehow I forgot to include my adjustment to it with my rebase commit.

This fix to the original test case is what prompted me to further exercise the CSVFormat.printWithQuotes() method with additional tests which are found in the JiraCsv263Test class.

**Comment by garydgregory** [comment]
https://issues.apache.org/jira/browse/CSV-263

**Comment by garydgregory** [comment]
@arcticgeek 
OK, looks good, I'll resolve the conflicts I just made in master and merge.

**Comment by garydgregory** [comment]
Closing, in git master now.

**Pull request closed without merging**
