### PR TITLE
CSVFormat#valiadte() does not account for allowDuplicateHeaderNames

### PR DESCRIPTION
**Pull request by LuckyIlam**
disabled duplicate check when duplicate header name is allowed

### CODE REVIEW

**Comment by hoaphan-ordermentum** [comment]
Anyone know when will this be released ? Just so the allowDuplicateHeaderNames introduced in 7.0 works as it should.

**Comment by garydgregory** [comment]
If you mean 1.7 ;-) then probably "within a few weeks" unless someone else gets to it before I do.

**Comment by hoaphan-ordermentum** [comment]
> If you mean 1.7 ;-) then probably "within a few weeks" unless someone else gets to it before I do.

Any chance you can release now :P, I want to offer my help but I guess I can't just checkout the commit, tag and release.

**Comment by garydgregory** [comment]
I am in the middle of releasing Apache Commons Text 1.7, so this component will have to wait at least a couple of days. Our validation process for release candidate takes 72 hours, so in a perfect world we might get something out in a week or so, no guarantees.

**Comment by macsharker6** [comment]
I @garydgregory . Why in the 1.7 version the commit 'd6e494b44d85540923b39eb4956a704ecee295b1' is not present? Your commit is inside the last release:
https://github.com/apache/commons-csv/compare/commons-csv-1.7...master
but if I download the source code the modify is not present. When the next release will be?
Regards.

**Comment by garydgregory** [comment]
@macsharker6 
We might release 1.8 within a month or so.
Gary

**Comment by macsharker6** [comment]
Hi @garydgregory any update for the release 1.8? Thanks.

macsharker6

**Comment by garydgregory** [comment]
@macsharker6 I think a week or maybe two. I have two other releases to do first.

**Comment by macsharker6** [comment]
Thanks.

Regards.
macsharker6

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il giovedì 26 settembre 2019 20:13, Gary Gregory <notifications@github.com> ha scritto:

**Comment by macsharker6** [comment]
Hi @garydgregory  the 1.8 release will exit next week?
Regards.

**Comment by kensixx** [comment]
Hi, and good day @garydgregory , any updates on ver 1.8 release? =)

**Comment by garydgregory** [comment]
@kensixx I kicked off a release vote earlier today.

**Comment by kensixx** [comment]
Thanks so much for your response @garydgregory , looking forward to the next release! =)

**Comment by sahi123** [comment]
Hi, and good day @garydgregory , any updates on ver 1.8 release?

**Comment by macsharker6** [comment]
Hi @garydgregory on the web site:
https://commons.apache.org/proper/commons-csv/changes-report.html
the date of the version 1.8 release is not correct :

1.8 | 2019-02-01 | Feature and bug fix release (Java 8)

The correct date would be contain 2020 and not 2019 as year. Regards.

**Comment by garydgregory** [comment]
> Hi @garydgregory on the web site:
> https://commons.apache.org/proper/commons-csv/changes-report.html
> the date of the version 1.8 release is not correct :
> 
> 1.8 | 2019-02-01 | Feature and bug fix release (Java 8)
> 
> The correct date would be contain 2020 and not 2019 as year. Regards.

Fixed! TY.

**Pull request closed without merging**
